import { createApp } from 'vue'
import { createHead } from '@vueuse/head'

import App from './App.vue'
import './registerServiceWorker'
import router from './router'
import store from './store'
import PrimeVue from 'primevue/config';
import Dialog from 'primevue/dialog';
import PanelMenu from 'primevue/panelmenu';
import Button from 'primevue/button';
import Toolbar from 'primevue/toolbar';
import TieredMenu from 'primevue/tieredmenu';
import Tree from 'primevue/tree';
import InputText from 'primevue/inputtext';
import DataTable from 'primevue/datatable';
import Column from 'primevue/column';
import ColumnGroup from 'primevue/columngroup';     //optional for column grouping
import Badge from 'primevue/badge';
import Chip from 'primevue/chip';
import DeferredContent from 'primevue/deferredcontent';
import Fieldset from 'primevue/fieldset';
import Card from 'primevue/card';
import Panel from 'primevue/panel';
import FullCalendar from 'primevue/fullcalendar';
import Calendar from 'primevue/calendar';
import ToastService from 'primevue/toastservice';
import Toast from "primevue/toast";
import TabMenu from "primevue/tabmenu";
import DataView from 'primevue/dataview';
import InputMask from 'primevue/inputmask';
import Divider from 'primevue/divider';
import RadioButton from 'primevue/radiobutton';
import InputNumber from 'primevue/inputnumber';
import FileUpload from 'primevue/fileupload';
import Skeleton from 'primevue/skeleton';
import Password from 'primevue/password';
import Menu from 'primevue/menu';
import Paginator from 'primevue/paginator';
import Checkbox from 'primevue/checkbox';
import Dropdown from 'primevue/dropdown';
import Tooltip from 'primevue/tooltip';
import Textarea from 'primevue/textarea';
import Steps from 'primevue/steps';
import BlockUI from 'primevue/blockui';
import BadgeDirective from 'primevue/badgedirective';
import ToggleButton from 'primevue/togglebutton';
import ConfirmationService from 'primevue/confirmationservice';
import Listbox from 'primevue/listbox';
import TabView from 'primevue/tabview';
import TabPanel from 'primevue/tabpanel';
import Chips from 'primevue/chips';
import SelectButton from 'primevue/selectbutton';
import 'primevue/resources/themes/saga-blue/theme.css';
import './assets/vcms.css'
import 'primevue/resources/primevue.min.css';
import 'primeicons/primeicons.css';
import 'primeflex/primeflex.css';
import Avatar from 'primevue/avatar';
import Sidebar from 'primevue/sidebar';
import OverlayPanel from 'primevue/overlaypanel';
import Editor from 'primevue/editor';
import Splitter from 'primevue/splitter';
import SplitterPanel from 'primevue/splitterpanel';

const app = createApp(App);
const head = createHead();
app.use(head);
app.use(ToastService);
app.use(ConfirmationService);
app.use(store);
app.use(router);
app.use(PrimeVue, {ripple: true});
app.component('Dialog', Dialog);
app.component('Splitter', Splitter);
app.component('SplitterPanel', SplitterPanel);
app.component('Sidebar', Sidebar);
app.component('Button', Button);
app.component('PanelMenu', PanelMenu);
app.component('Toolbar', Toolbar);
app.component('TieredMenu', TieredMenu);
app.component('Tree', Tree);
app.component('InputText', InputText);
app.component('DataTable', DataTable);
app.component('Column', Column);
app.component('ColumnGroup', ColumnGroup);
app.component('Badge', Badge);
app.component('Avatar', Avatar);
app.component('Chip', Chip);
app.component('DeferredContent', DeferredContent);
app.component('Fieldset', Fieldset);
app.component('Card', Card);
app.component('Panel', Panel);
app.component('FullCalendar', FullCalendar);
app.component('Calendar', Calendar);
app.component('Toast', Toast);
app.component('OverlayPanel', OverlayPanel);
app.component("TabMenu", TabMenu);
app.component("DataView", DataView);
app.component("InputMask", InputMask);
app.component("Divider", Divider);
app.component("RadioButton", RadioButton);
app.component("InputNumber", InputNumber);
app.component("FileUpload", FileUpload);
app.component("Skeleton", Skeleton);
app.component("Password", Password);
app.component("Menu", Menu);
app.component("Paginator", Paginator);
app.component("Checkbox", Checkbox);
app.component("Dropdown", Dropdown);
app.component("Editor", Editor);
app.component("Textarea", Textarea);
app.component("Steps", Steps);
app.component("BlockUI", BlockUI);
app.component("ToggleButton", ToggleButton);
app.component("Listbox", Listbox);
app.component("TabView", TabView);
app.component("TabPanel", TabPanel);
app.component("SelectButton", SelectButton);
app.component("Chips", Chips);
app.directive('tooltip', Tooltip);
app.directive('badge', BadgeDirective);
app.mount('#app');